controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - corredera
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
        - effort
      gains:
        corredera:
          p: 100.0
          d: 1.0
          i: 1.0
          i_clamp: 1.0

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      parameters:
        publish_rate: 50  # Hz

joint_trajectory_controller:
  ros__parameters:
    joints:
      - corredera
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: false
    gains:
      corredera:
        p: 100.0
        d: 1.0
        i: 1.0
        i_clamp: 1.0

joint_state_broadcaster:
  ros__parameters:
    joints:
      - corredera
      - pendulo