# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - scara_controller

  scara_controller:
    type: FollowJointTrajectory
    joints:
      - hombro
      - codo
      - falange
      - muneca
    action_ns: follow_joint_trajectory  ### Agregado despues del asistente
    default: true                       ### Agregado despues del asistente