controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - corredera
        - pendulo
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      gains:
        corredera:
          p: 100.0
          d: 1.0
          i: 1.0
          i_clamp: 1.0
        pendulo:
          p: 100.0
          d: 1.0
          i: 1.0
          i_clamp: 1.0

joint_trajectory_controller:
  ros__parameters:
    joints:
      - corredera
      - pendulo
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: false

joint_state_broadcaster:
  ros__parameters:
    joints:
      - corredera
      - pendulo